# Generated by Django 4.1.7 on 2023-03-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
