# Generated by Django 4.1.7 on 2023-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0002_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
