# Generated by Django 4.1.7 on 2023-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardkinds',
            name='bonus',
        ),
        migrations.AddField(
            model_name='cardkinds',
            name='virtual',
            field=models.BooleanField(default=True),
        ),
    ]
