# Generated by Django 4.1.7 on 2023-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0008_remove_cardkinds_bonus_cardkinds_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardkinds',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
