# Generated by Django 4.1.7 on 2023-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0010_depositkinds_pict'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditkinds',
            name='pict',
            field=models.ImageField(null=True, upload_to='images/credits/'),
        ),
    ]
