# Generated by Django 4.1.7 on 2023-04-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0013_remove_deposit_iin_remove_deposit_pin_card_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='cvv',
        ),
    ]
