# Generated by Django 4.1.7 on 2023-04-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0014_remove_deposit_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
