# Generated by Django 4.1.7 on 2023-04-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0015_deposit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=500, null=True),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('sum_vid', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('bik', models.CharField(max_length=9)),
                ('iban', models.CharField(max_length=34)),
                ('percent', models.FloatField()),
                ('month_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_info.creditkinds')),
            ],
        ),
    ]
