# Generated by Django 4.1.7 on 2023-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0021_rename_company_paymentcompanytransfers_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcompanytransfers',
            name='name',
        ),
        migrations.AddField(
            model_name='paymentcompanytransfers',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
