# Generated by Django 4.1.7 on 2023-04-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0026_alter_paymentcompanytransfers_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransfer',
            name='recipient_deposit',
        ),
        migrations.RemoveField(
            model_name='deposittransfer',
            name='sender_card',
        ),
        migrations.DeleteModel(
            name='CardTransfer',
        ),
        migrations.DeleteModel(
            name='DepositTransfer',
        ),
    ]
