# Generated by Django 4.1.7 on 2023-04-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0027_remove_deposittransfer_recipient_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='принимающий', to='bank_info.deposit')),
                ('sender_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_info.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='принимающий', to='bank_info.card')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_info.card')),
            ],
        ),
    ]
