# Generated by Django 4.1.7 on 2023-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0028_deposittransfer_cardtransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='deposittransfer',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
