# Generated by Django 4.1.7 on 2023-04-29 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0029_alter_deposittransfer_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_info.card')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_info.credit')),
            ],
        ),
    ]
