# Generated by Django 4.1.7 on 2023-05-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0030_credittransfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_status',
            field=models.BooleanField(default=False),
        ),
    ]
